---
name: DBD-Mock
version: 1.36
author:
  - 'Chris Winters E<lt>chris@cwinters.comE<gt>'
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
  - 'Rob Kinyon E<lt>rob.kinyon@gmail.comE<gt>'
abstract: Mock database driver for testing
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.3
  perl: 5.6.0
build_requires:
  Test::More: 0.47
provides:
  DBD::Mock:
    file: lib/DBD/Mock.pm
    version: 1.36
  DBD::Mock::Pool:
    file: lib/DBD/Mock.pm
  DBD::Mock::Pool::db:
    file: lib/DBD/Mock.pm
  DBD::Mock::Session:
    file: lib/DBD/Mock.pm
  DBD::Mock::StatementTrack:
    file: lib/DBD/Mock.pm
  DBD::Mock::StatementTrack::Iterator:
    file: lib/DBD/Mock.pm
  DBD::Mock::db:
    file: lib/DBD/Mock.pm
  DBD::Mock::dr:
    file: lib/DBD/Mock.pm
  DBD::Mock::st:
    file: lib/DBD/Mock.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
