---
name: DBD-Mock
version: 1.32
author: ~
abstract: Mock database driver for testing
license: perl
requires:
  DBI: 1.3
  perl: 5.6.0
build_requires:
  Test::More: 0.47
provides:
  DBD::Mock:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::Pool:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::Pool::db:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::Session:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::StatementTrack:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::StatementTrack::Iterator:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::db:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::dr:
    file: lib/DBD/Mock.pm
    version: 1.32
  DBD::Mock::st:
    file: lib/DBD/Mock.pm
    version: 1.32
generated_by: Module::Build version 0.2611
